version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-runner}  # Use 'builder' for development, 'runner' for production
    container_name: discord-tempvoice-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ${DEV_SOURCE_MOUNT:-/dev/null}:/app/src  # Mount source code in development
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - NODE_ENV=${NODE_ENV:-production}
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3" 