services:
  bot:
    image: ghcr.io/phoenirxraph/discord-tempvoice-bot:latest
    container_name: discord-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    healthcheck:
      test: ["CMD", "bun", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3" 