name: Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: discord-tempvoice-bot
          
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        
      - uses: oven-sh/setup-bun@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          bun-version: latest
          
      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: bun install
        
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: bun run build 