name: Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write
  actions: write
  statuses: write
  checks: write
  deployments: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    
    steps:
      - uses: googleapis/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: discord-tempvoice-bot
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Maintenance","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"refactor","section":"Refactor","hidden":false},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"test","section":"Testing","hidden":false}
            ]

  build-and-publish:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
          
      - name: Install dependencies
        run: bun install
        
      - name: Run tests
        run: bun test
        
      - name: Build
        run: bun run build
        
      - name: Create release artifact
        run: |
          tar -czf discord-bot-${{ needs.release.outputs.tag_name }}.tar.gz \
            dist/ \
            package.json \
            bun.lockb \
            README.md \
            LICENSE \
            docker-compose.yml \
            Dockerfile
            
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release.outputs.tag_name }}
          files: |
            discord-bot-${{ needs.release.outputs.tag_name }}.tar.gz
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: true 